Awards = {
    "Most Likely to Be AFK",
    "Professional Button Masher",
    "Main Character",
    "Certified Chaos Agent",
    "Tried Their Best",
    "Most Confused Player",
    "Most Dramatic Deaths",
    "Loudest",
    "Suspiciously Quiet",
    "Most Trustworthy",
    "sus",
    "NPC Energy",
    "90% Luck, 10% WiFi",
    "Emotionally Attached to Respawn",
    "Blamed Lag the Most",
    "Pressed All the Wrong Buttons",
    "Forced to Play",
    "Tactical Genius (Unverified)",
    "Almost Clutched It",
    "Best Strategic Panic",
    "Advanced Retreat Specialist",
    "Creative Use of Mistakes",
    "Master of Accidental Plays",
    "Free Points Provider",
    "Respawn Simulator Champion",
    "Carried the Enemy Team",
    "Most Generous with Deaths",
    "Got April Fooled",
    "Reality Questioner",
    "Victim of the Game Engine",
    "Gravity Tester",
    "Certified Bug Finder",
    "Broke the Laws of Physics",
    "Most Likely to Be a Bot",
    "Played Like Nobody Was Watching",
    "The Reason We Have Rules",
    "MVP (Mystery Value Player)",
    "Honorable Mention for Unknown Reasons",
    "Minimal Effort Maximum Impact",
    "Accidental Speedrunner",
    "Lost But Confident",
    "Knows Something We Don't",
    "Just Happy to Be Here",
    "Carried by Luck",
    "Tutorial Skipped",
    "Certified Button Enjoyer",
    "Elite Standing Still",
    "Reaction Time Pending",
    "Almost Did Something",
    "Spectator in Disguise",
    "Skill Under Construction",
    "Top 10 Anime Betrayals",
    "Unexpectedly Present",
    "Aim Not Found",
    "Keyboard Warrior",
    "Strategically Lost",
    "100% Commitment to Chaos",
    "Mildly Threatening",
    "Unintended Gameplay",
    "Confused",
    "Running Simulator Enthusiast",
    "Professional Respawner",
    "Big Plans, No Execution",
    "Unpredictable",
    "Failed Successfully",
    "Certified Oops Moment",
    "High Ping Energy",
    "Courage Over Skill",
    "Map Explorer",
    "Accidentally Impressive",
    "Professional",
    "The Plot Twist",
    "Background Noise",
    "Powered by Panic",
    "Zero Accuracy",
    "Unlicensed Tactics",
    "Peak Confusion",
    "Did It For The Content",
    "Actually Cracked",
    "Built Different",
    "Clutch Master",
    "Unironically Good",
    "MVP Energy",
    "Peak Gamer Performance",
    "Lowkey Insane",
    "Too Smooth",
    "Clean Play",
    "Big Brain Moments",
    "Top Tier Behavior",
    "Outplayed Everyone (Including Themselves)",
    "Better Than Expected",
    "Went Crazy For No Reason",
    "Effortlessly Impressive",
    "The Comeback",
    "Silent But Deadly",
    "Underrated",
    "Built for This Game",
    "Deserved to Win",
    "Momentum Machine",
    "Consistently Inconsistent",
    "Luck or Skill?",
    "Natural Talent",
    "Smooth Operator",
    "Clean Execution",
    "Better Every Respawn",
    "Did Something Right",
    "Smart Play",
    "Dangerous Player",
    "Questionable Decisions",
    "Pensive",
    "Relieved",
    "Most Improved (From Last Death)",
    "Best Comeback",
    "Best Newcomer",
    "Best Hat",
    "Best Skin",
    "Best Name",
    "Best Use of Environment",
    "Best Use of Weapons",
    "Best Use of Power-Ups",
    "Most Stylish",
    "Most Creative",
    "Most Unpredictable",
    "Most Entertaining",
    "Most Elegant",
    "Most Brutal",
    "Most Hilarious",
    "Most Ridiculous",
    "Most Memorable",
    "Most Iconic",
    "Best Timing",
    "Best Movement",
    "Best Aim",
    "Best Survival Skills",
    "Best Decision Making",
    "Best Awareness",
    "Best Positioning",
    "Best Escape",
    "Best Chase",
    "Best Recovery",
    "Best Adaptation",
    "Best Risk Taker",
    "Best Comeback Attempt",
    "Best Coordination",
    "Best Improvisation",
    "Best Momentum",
    "Best Control",
    "Best Execution",
    "Most Dedicated",
    "Most Fearless",
    "Most Determined",
    "Most Aggressive",
    "Most Tactical",
    "Most Efficient",
    "Most Consistent",
    "Most Focused",
    "Most Alert",
    "Most Resilient",
    "Most Clutch",
    "Most Calculated",
    "Most Dangerous",
    "Most Dominant",
    "Most Slippery",
    "Most Elusive",
    "Most Persistent",
    "Most Reliable",
}