Package.Require("Config.lua")
Package.Require("Utils.lua")
Package.Require("Log.lua")
Package.Require("Chat.lua")
Package.Require("Hats.lua")
Package.Require("Skins.lua")
Package.Require("Breakable.lua")
Package.Require("Scores.lua")
Package.Require("MelonGun.lua")
Package.Require("Bonker.lua")
Package.Require("Player.lua")
Package.Require("Controls.lua")
Package.Require("PowerUp.lua")
Package.Require("Test.lua")

Server.Subscribe("Tick", function(delta)
    for _, powerUp in pairs(PowerUp.GetAll()) do
        powerUp:Tick(delta)
    end
end)
